### ISSUE TITLE
Text not translated on initial load

### ISSUE THREAD

**Issue by marius-kildedal** [Trekels/vue-trans#1]
When the component loads the text is still the trans sting.

Example: i have a button with the text 'btn.get_report' translate string. 
When i push it it gets translated, and all the other text gets translated.

But when the page has first loaded and nothing is pressed the symfony trans text is shown. 

Any tips to 'kickstart' the translation?

**Comment by Trekels** [comment]
@marius-kildedal Can you give a small code sample on how you use the filter ?

**Comment by marius-kildedal** [comment]
vue file:
`<template v-else="gridConfig.test">
                                <button type="submit"> {{ 'btn.get_report' | trans }} </button>
</template>`
twig file: 
`window.translations = {
            'btn.close': '{{ 'btn.close' | trans }}',
            'btn.get_report': '{{ 'btn.get_report' | trans }}',
}`

as soon as a click a button, all other translation gets translated to the correct text

**Comment by marius-kildedal** [comment]
video showing an example: 
https://www.useloom.com/share/9b1696f6fec04fcb9bdc11074ebff43d

**Comment by Trekels** [comment]
@marius-kildedal And how is the filter registered. Is the issue with this specific component?

**Comment by marius-kildedal** [comment]
I am importing it 
`import transFilter from 'vue-trans';` and using it 
`Vue.use(transFilter);` in the app.js file. 

Currently we only use this one component to handle reporting.

**Comment by Trekels** [comment]
@marius-kildedal I have been able to replicate the issue, I will notify you when I find a solution.

**Comment by Trekels** [comment]
@marius-kildedal Can you check if you set the translations on the window object before you instantiate your vue app?

**Comment by marius-kildedal** [comment]
Sorry for the late reply. 
I moved the `<script>
        window.translations = {) </script>` object before vue is instantiated, and this seems to work fine.
This looked like the solution.
